baseURL = 'https://log.j38.uk/'
languageCode = 'en-us'
title = 'j38.uk'
theme = 'papermod'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enable or disable HTML rendering in Markdown content
      unsafe = true 
    [markup.goldmark.extensions]
      # Enable or disable typographer extension
      typographer = true
      # Enable or disable table extension
      table = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "quotations"
    name = "Quotations"
    url = "/quotations/"
[taxonomies]
  tag = "tags"
  category = "categories"