baseURL = 'https://log.j38.uk/'
languageCode = 'en-us'
title = 'j38.uk'
theme = 'papermod'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
    [markup.goldmark.extensions]
      typographer = true
      table = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "readings"
    name = "Readings"
    url = "/readings"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  hideSummary = true
