baseURL = 'https://log.j38.uk/'
languageCode = 'en-us'
title = 'j38.uk'
theme = 'papermod'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
    [markup.goldmark.extensions]
      typographer = true
      table = true
[menu]
  [[menu.main]]
    identifier = "quotations"
    name = "Quotations"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes"
    weight = 2
  [[menu.main]]
    identifier = "techne"
    name = "Techne"
    url = "/techne"
    weight = 2
  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links"
    weight = 3
  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  hideSummary = true
  pluralizeListTitles = false
